#DEFINITIONS
BLUE = 0
RED = 1

#DEFAULTS:
THRESHOLD = 0.5
RATE_OF_INCREASE = 1.0
RESOURCES = 30
NUM_ROUNDS = 3
MAX_BOOST = 0.2
STEEPNESS_K = 3.0

#NETWORK DEFAULTS:
POLARIZATION = 0.55
NUM_NODES = 300 #number of nodes in each battlefield
NUM_BATTLEFIELDS = 10
WATTS_STROGATZ_K = 10
WATTS_STROGATZ_P = 0.5

